 Object {
    "alias": "pesto-italian-craft-kitchen-mission-valley-san-diego",
    "categories": Array [
      Object {
        "alias": "pizza",
        "title": "Pizza",
      },
      Object {
        "alias": "italian",
        "title": "Italian",
      },
    ],
    "coordinates": Object {
      "latitude": 32.769922,
      "longitude": -117.146673,
    },
    "display_phone": "(619) 679-9030",
    "distance": 2395.1583596443134,
    "id": "qXRzQERT-WFDo6spPeQwZw",
    "image_url": "https://s3-media2.fl.yelpcdn.com/bphoto/OVbDWc3JJWaxlr_HftQnSg/o.jpg",
    "is_closed": false,
    "location": Object {
      "address1": "1652 Camino Del Rio N",
      "address2": "",
      "address3": null,
      "city": "San Diego",
      "country": "US",
      "display_address": Array [
        "1652 Camino Del Rio N",
        "San Diego, CA 92108",
      ],
      "state": "CA",
      "zip_code": "92108",
    },
    "name": "Pesto Italian Craft Kitchen - Mission Valley",
    "phone": "+16196799030",
    "price": "$$",
    "rating": 4.5,
    "review_count": 344,
    "transactions": Array [
      "pickup",
      "delivery",
    ],
    "url": "https://www.yelp.com/biz/pesto-italian-craft-kitchen-mission-valley-san-diego?adjust_creative=W1dNi6Ziy5O0z-dk2LOQow&utm_campaign=yelp_api_v3&utm_medium=api_v3_business_search&utm_source=W1dNi6Ziy5O0z-dk2LOQow",
  },